apiVersion: v1
baseDomain: '{config.ocp.baseDomain}'
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: '{config.ocp.clusterName}'
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: '{config.ocp.awsRegion}'
publish: External
pullSecret: '{config.ocp.pullSecret}'
sshKey: '{config.ocp.sshKey}'