# gitpod.io/#github.com/CaravanaCloud/cloud-janitor
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build cloud-janitor
    init: mvn clean verify -DskipTests
    command: |
      mvn install:install-file -Dfile=lib/AthenaJDBC42-2.0.35.1000.jar -DgroupId=com.syncron.amazonaws -DartifactId=simba-athena-jdbc-driver -Dversion=2.0.35.1000 -Dpackaging=jar &&
      sudo ln -s /workspace/cloud-janitor/target/jpackage/app_image/cloud-janitor/bin/cloud-janitor /usr/local/bin/cloud-janitor &&
      cloud-janitor -cj:version

ports:
  - port: 3306
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 13370
    onOpen: ignore
  - port: 13371
    onOpen: ignore
  - port: 13372
    onOpen: ignore
  - port: 13373
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
#    - GitHub.copilot

