cj:
  aws:
    regions:
      - ap-northeast-1
      - us-west-2
    roles:
      - arn: arn:aws:iam::192912639870:role/sampleRole1

# export ASSUME_ROLE=$(aws sts assume-role --role-arn "arn:aws:iam::192912639870:role/sampleRole1" --role-session-name cli-session)
# export AWS_ACCESS_KEY_ID=$(echo $ASSUME_ROLE | jq -r '.Credentials.AccessKeyId')
# export AWS_SECRET_ACCESS_KEY=$(echo $ASSUME_ROLE | jq -r '.Credentials.SecretAccessKey')
# export AWS_SESSION_TOKEN=$(echo $ASSUME_ROLE | jq -r '.Credentials.SessionToken')
