accounts:
  "192912639870": {} # ccsandbox

account-blocklist:
  - "192912699999"

resource-types:
  excludes:
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMInstanceProfile
    - IAMInstanceProfileRole
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMPolicy
    - IAMRole
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMSAMLProvider
    - IAMServerCertificate
    - IAMServiceSpecificCredential
    - IAMSigningCertificate
    - IAMUser
    - IAMUserAccessKey
    - IAMUserGroupAttachment
    - IAMUserPolicy
    - IAMUserPolicyAttachment
    - IAMUserSSHPublicKey
    - IAMVirtualMFADevice
    - Route53HealthCheck
    - Route53HostedZone
    - Route53ResolverEndpoint
    - Route53ResolverRule
    - Route53ResourceRecordSet
    - Route53TrafficPolicy

regions:
  - global
  - us-east-2
  - us-east-1
  - us-west-1
  - us-west-2
  - af-south-1
  - ap-east-1
  - ap-southeast-3
  - ap-south-1
  - ap-northeast-3
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ca-central-1
  - cn-north-1
  - cn-northwest-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-south-1
  - eu-west-3
  - eu-north-1
  - me-south-1
  - sa-east-1
