cj:
  tasks:
    - name: "cowsay"
      maturity: "stable"
      description: "Cowsay is a configurable talking cow"
      bypass:
        - "cowsay"
        - "-s"
        - "{args}"
        - "{dryRunFlag}"
        - "{mapa.get('uala')}"
        - ":)"

    - name: "aws-nuke-bypass"
      bypass:
        - "aws-nuke"
        - "--force"
        - "{dryRunFlag}"
        - "--config"
        - "{configFilePath}"

    - name: "aws-ping"
      description: "Ping AWS to check authentication"
      repeat: "each_identity_region"
      #TODO: Support changing environment on bypass so that identity changes
      bypass:
        - "aws"
        - "sts"
        - "get-caller-identity"

    - name: "aws-subtitles"
      description: "Transcribe and translate videos"
      steps:
        - run: "aws-transcribe"
        - run: "aws-translate"

    - name: "aws-nuke"
      description: "Delete resources in an AWS account"
      repeat: "each_identity"
      templates:
        - template: "aws-nuke.qute.yaml"
          output: "aws-nuke.yaml"
      install:
        check: "aws-nuke version"
        packages:
          executables:
            - path: "aws-nuke-v2.21.2-linux-amd64"
              link: "aws-nuke"
          darwin_amd64: "https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-darwin-amd64.tar.gz"
          darwin_arm64: "https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-darwin-arm64.tar.gz"
          linux_amd64: "https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-linux-amd64.tar.gz"
          linux_arm64: "https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-linux-arm64.tar.gz"
          linux_arm7: "https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-linux-arm7.tar.gz"
          windows_amd64: "https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-windows-amd64.zip"
      bypass:
          # - "echo"
          - "aws-nuke"
          - "--force"
          - "{dryRunFlag}"
          - "--config"
          - "{templatePath.get('aws-nuke.yaml')}"
