apiVersion: 'v1'
baseDomain: '{config.ocp.baseDomain}'
credentialsMode: 'Manual'
metadata:
  name: '{config.ocp.clusterName}'
platform:
  aws:
    region: '{config.ocp.awsRegion}'
publish: 'External'
pullSecret: '{config.ocp.pullSecret}'
sshKey: '{config.ocp.sshKey}'