cj:
  task: cleanup-aws
  dryRun: true
  aws:
    regions:
      - ap-northeast-1
      - us-west-2
    roles:
      -
        alias: faermanj_cc_to_sandox
        arn: arn:aws:iam::192912639870:role/faermanj_cc_to_sandbox
      -
        alias: invalid_role
        arn: arn:aws:iam::123456789012:role/this_wont_work

# TODO: Implement account exclude
#    exclude:
#          #      accounts:
#        - 269733383066
