version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "janitor-config-rules"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l7hkls1wbdn7"
s3_prefix = "janitor-config-rules"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
