name: Cleanup an AWS Account (Dry Run)

on: [workflow_dispatch]

env:
  TT_TASK: cleanup-aws
  TT_DRYRUN: true
  TT_AWS_REGIONS: ap-northeast-1,eu-west-2
  TT_AWS_CLEANUP_PREFIX: rhnb-

jobs:
  all-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Task Tree
        uses: CaravanaCloud/task-tree@v1.0.20220318114521

