---
name: 2 Nuke AWS sandbox

on:
  workflow_dispatch: { }
  schedule:
    - cron: "00 5 * * *"

jobs:
  build:
    name: Cloud Janitor Job
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
      URL: https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-linux-amd64.tar.gz
      OUTPUT: /tmp/aws-nuke/aws-nuke-v2.21.2-linux-amd64.tar.gz

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Check AWS Authentication
        run: aws sts get-caller-identity

      - name: checkout code
        uses: actions/checkout@v2

      - name: check config
        run: cat ./config/aws-nuke/ccsandbox.yaml

      - name: MKDIR
        run: mkdir /tmp/aws-nuke

      - name: Download aws-nuke
        run: curl -Ls $URL --output $OUTPUT

      - name: Extract aws-nuke
        run: tar zxvf $OUTPUT -C /tmp/aws-nuke

      - name: Move aws-nuke to path
        run: sudo mv /tmp/aws-nuke/aws-nuke-v2.21.2-linux-amd64 /usr/local/bin/aws-nuke

      - name: List resource types
        run: aws-nuke resource-types | tee aws-nuke.log

#      - name: Try aws-nuke
#        run: aws-nuke -c ./config/aws-nuke/ccsandbox.yaml --no-dry-run --force --force-sleep 3 | tee aws-nuke.log
#        continue-on-error: true

      - name: Preserve log
        uses: actions/upload-artifact@v3
        with:
          name: aws-nuke.log
          path: "aws-nuke.log"
          retention-days: 14