---
name: 0 Janitor AWS sandbox [CLI]

on:
  workflow_dispatch: { }
  schedule:
    - cron: "00 4 * * *"

jobs:
  build:
    name: Cloud Janitor Job
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
      URL: https://github.com/CaravanaCloud/cloud-janitor/releases/download/v1.7.1/cloud-janitor.zip
      OUTPUT: /tmp/cloud-janitor/cloud-janitor.zip

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Check AWS Authentication
        run: aws sts get-caller-identity

      - name: Check AWS Authentication
        run: aws sts get-caller-identity

      - name: checkout code
        uses: actions/checkout@v2

      - name: check config
        run: cat ./config/aws-nuke/ccsandbox.yaml

      - name: MKDIR
        run: mkdir /tmp/cloud-janitor

      - name: Download aws-nuke
        run: curl -Ls $URL --output $OUTPUT

      - name: Extract cloud-janitor
        run: unzip -d /tmp/cloud-janitor $OUTPUT

      - name: debug
        run: find /tmp/cloud-janitor

      - name: Move to path
        run: sudo mv /tmp/cloud-janitor/bin/cloud-janitor /usr/local/bin/cloud-janitor

      - name: Go jantor
        run: cloud-janitor
        continue-on-error: true
        env:
          CJ_TASK: "aws-nuke"
          CJ_CAPABILITIES: "all"
          CJ_AWS_REGIONS_0_: "ap-northeast-1"
          CJ_AWS_REGIONS_1_: "eu-south-2"
          CJ_AWS_REGIONS_2_: "us-west-2"
          CJ_AWS_REGIONS_3_: "eu-west-1"
          QUARKUS_LOG_CONSOLE_LEVEL: "DEBUG"

      - name: Preserve log
        uses: actions/upload-artifact@v3
        with:
          name: cloud-janitor.log
          path: "cloud-janitor.log"
          retention-days: 14