---
name: Nuke sandbox AWS account every night

on:
  workflow_dispatch: { }
  schedule:
    - cron: "33 3 * * *"

jobs:
  build:
    name: Cloud Janitor Job
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Check AWS Authentication
        run: aws sts get-caller-identity

      - name: Nuke AWS Account
        uses: CaravanaCloud/cloud-janitor@v1.7.0
        env:
          CJ_TASK: "aws-nuke"
          CJ_AWS_REGION: "us-west-2"