---
name: 0 Run cloud-janitor github action every push.

on:
  workflow_dispatch: { }
  push:
    branches:
      - "**"

jobs:
  build:
    name: Cloud Janitor Job
    runs-on: ubuntu-latest
    steps:
      - name: Cloud Janitor
        uses: CaravanaCloud/cloud-janitor@v1.7.2

