name: Build a new release from tag

on:
  push:
    tags:
      - 'tasktree-*'

jobs:
  all-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kubectl Plugin
        uses: ./.github/workflows/build-kubctl-plugin.yml

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tt-cli/target/kubectl-tasks
          asset_name: kubectl-tasks
          asset_content_type: application/octet-stream
