name: Build a new release from tag

on:
  push:
    tags:
      - 'tasktree-*'

env:
  REF_NAME: ${{ github.ref_name }}

jobs:
  build-uberjar:
    uses: ./.github/workflows/build-uberjar.yml

  build-rpm:
    needs: build-uberjar
    runs-on: ubuntu-latest
    steps:
      - name: Download uberjar
        uses: actions/download-artifact@v2
        with:
          name: tasktree-runner.jar

      - name: Lookup version
        id: lookup_version
        run: |
          VERSION=$(echo "$REF_NAME" | cut -d\- -f2-)
          RELEASE=1
          ARCH=x86_64
          RPM_PKG="./tasktree-$VERSION-$RELEASE.$ARCH.rpm"
          echo ::set-output name=VERSION::$VERSION
          echo ::set-output name=RELEASE::$RELEASE
          echo ::set-output name=RPM_PKG::$RPM_PKG

      - name: Before package
        run: echo "RPM_PKG=${{steps.lookup_version.outputs.RPM_PKG}}"

      - name: Trust but verify
        run: find .

      - name: Build the package
        run: |
          jpackage --input "$PWD" --main-jar "tasktree-runner.jar" \
            --name "tasktree" \
            --main-class "tasktree.Main" \
            --type "rpm" \
            --java-options "--enable-preview" \
            --app-version "${{steps.lookup_version.outputs.VERSION}}" \
            --linux-app-release "${{steps.lookup_version.outputs.RELEASE}}" \
            --description "TaskTree RPM Package" \
            --vendor "CaravanaCloud" 

      - name: Alias to unversioned package name
        run: ln -s "${{steps.lookup_version.outputs.RELEASE}}" "./tasktree-cli.rpm"

      - name: Upload rpm
        uses: actions/upload-artifact@v2
        with:
          name: tasktree-cli.rpm
          path: ./tasktree-cli.rpm

  upload-artifacts:
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download uberjar
        uses: actions/download-artifact@v2
        with:
          name: tasktree-runner.jar

      - name: Download RPM
        uses: actions/download-artifact@v2
        with:
          name: tasktree-cli.rpm

      - name: Trust but verify
        run: find .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Release UberJar
        id: release-uberjar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tasktree-runner.jar
          asset_name: tasktree-runner.jar
          asset_content_type: application/octet-stream

      - name: Release RPM
        id: release-rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tasktree-cli.rpm
          asset_name: tasktree-cli.rpm
          asset_content_type: application/octet-stream
