name: Test PRs and pushes to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup GraalVM action
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.0.0.2
          native-image: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}
        env:
          AWS_REGION: us-west-2

      - name: Test with Maven
        continue-on-error: true
        run: mvn -B test surefire-report:report jacoco:report ${MVN_OPTS}
        env:
          MVN_OPTS: -DskipTests=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Debug
        run: find .

      - name: Upload surefire reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
          retention-days: 14

      - name: Upload site reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-site
          path: target/site
          retention-days: 14
